# Generated by Django 5.1.7 on 2025-03-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questrion_Text',
            new_name='question_Text',
        ),
    ]
