# Generated by Django 5.1.7 on 2025-03-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_questrion_text_question_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_Text',
            new_name='question_text',
        ),
    ]
